<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Summary\Module'                        => __DIR__ . '/Module.php',
    'Summary\Controller\SummaryController' => __DIR__ . '/src/Summary/Controller/SummaryController.php',
    'SummaryTest\Framework\TestCase'        => __DIR__ . '/tests/Summary/Framework/TestCase.php',
    'SummaryTest\SampleTest'                => __DIR__ . '/tests/Summary/SampleTest.php',
);
